### ISSUE TITLE
您好，请教一下代码的问题

### ISSUE THREAD

**Issue by ithok** [WuYunfan/Inductive-Graph-Convolution-Network-for-Recommendation#1]
作者您好！我是首先在arxiv上看到了您文章的预印本，然后当时留下了这个地址。

今年在SIGIR上看到了INMO，个人感觉两篇文章的思路是一样的，然后INMO貌似文章内没有声明开源，具体想问的就是二者是否相同？官方代码是否开源，如果暂未开源，何时开源呢？

非常感谢！

**Comment by WuYunfan** [comment]
您好，两篇文章是一样的，这个repo的名字是INMO的之前版本，INMO文章内留了github地址也是这个。
