### ISSUE TITLE
您好，请问一下选择模板项目的问题

### ISSUE THREAD

**Issue by ithok** [WuYunfan/Inductive-Graph-Convolution-Network-for-Recommendation#2]
作者您好！
因为当时得到您INMO和IGCN文章一致的时候我就没有认真再去看INMO这篇文章了，不过最近有涉及到类似方面，所以重看了一遍，想了解一下INMO和IGCN是否在文章内容上做了一些更正，比如对于模板用户和模板项目的选取？

**Comment by WuYunfan** [comment]
你好，目前在具体实现上还是按照normalized degree排序的，应该是和原来的IGCN一样，好像也没用正则化。具体公式可见INMO文章4.2的第三段。

**Comment by ithok** [comment]
好的，感谢您的回复！
