### ISSUE TITLE
请教一下项目运行的问题

### ISSUE THREAD

**Issue by ithok** [WuYunfan/Inductive-Graph-Convolution-Network-for-Recommendation#3]
作者您好，我下载了代码和您准备的本文的数据集，因为您没有具体介绍项目的环境，我就用了以前配好的dgl，在装了几个依赖后总算没有报错，然后把run文件夹下的run.py移动到了主目录，但是依旧跑不起来，想请教一下本文代码的具体使用方法是什么？

具体报错如图
![image](https://user-images.githubusercontent.com/37830886/177499503-d200144d-c25b-4910-9345-95abfa66da32.png)

除了上述操作，我是还把本文数据集直接拉到了主目录。

望您解惑，不胜感激！

**Comment by WuYunfan** [comment]
具体运行方法应该是先把数据放到igcn_cf/data 目录，然后再python -u -m run.run
您的具体报错好像没截图到，可以再截图一下报错的红字吗？

**Comment by ithok** [comment]
您好，我把报错的项目删了从头来过了，所以没法截了，具体的就是感觉run运行了好几次，然后显存爆了。
图里的就是using backdone跳了好几次直到我资源不足（我不确定这是不是代码的就长这样）。

data我已经放到了指定目录，但是python -u -m run.run 报错提示Error while finding module specification for 'run.run' (ModuleNotFoundError: No module named 'run')

我原来能跑起来（能跑出报错的情况）是我把run文件夹下的run.py移动了根目录下。

运行python -u -m run.run之前还需要什么额外操作吗？

**Comment by WuYunfan** [comment]
运行python -u -m run.run的目录应该是主目录igcn_cf
报多次using backdone是因为windows系统，您可以把config里面的dataloader_num_workers改成0

**Comment by ithok** [comment]
您好，应该算已经跑起来了，但是过程好像并没有输出数据
![image](https://user-images.githubusercontent.com/37830886/177703455-6a64e0e5-aa4b-4c3a-a2bd-43634c4e65cb.png)
后台倒是有显示资源占用，请问这种状况正常吗
![image](https://user-images.githubusercontent.com/37830886/177703609-e7c8096b-4e13-4d23-a1b3-149b2f82392c.png)

**Comment by WuYunfan** [comment]
输出的数据在igcn_cf/run/run/log.txt

**Comment by ithok** [comment]
好的，感谢您的回复！

**Comment by ithok** [comment]
您好，请问INMO怎么在checkpoints重新训练呢，还是需要自己写相关的接口？

**Comment by WuYunfan** [comment]
这个可能需要自己写一下，大概主要就是调用model里的load，然后再接着调用trainer里的train就行了

**Comment by ithok** [comment]
OK

Yunfan Wu ***@***.***> 于2022年8月8日周一 12:03写道：
