### ISSUE TITLE
请教一下如何运行inductiveSetting

### ISSUE THREAD

**Issue by ShengGuanWSU** [WuYunfan/Inductive-Graph-Convolution-Network-for-Recommendation#4]
目前代码在ProcessedDataset中有assert 使得len(train_data)=len(val_data)=len(test_data). 请教在inductive setting 中是否需要train_data 中user id 与val_data 中user id 保持一致（即val_data 中不会出现相较train_data 的新user)?  除需要用inductive_eval 之外还需要其他改动么？

**Comment by WuYunfan** [comment]
我现在的代码实现是要求len(train_data)=len(val_data)=len(test_data)，在进行实验的时候其实是在训练的时候用一个dataset，测试的时候用另一个dataset，这两个dataset的用户商品数不一样，详情可见https://github.com/WuYunfan/igcn_cf/blob/master/run/dropui/imf_dropui.py里的实现
