### ISSUE TITLE
请教一下IGCN 中 inductive_rep_layer 模块的实现逻辑.

### ISSUE THREAD

**Issue by soujie** [WuYunfan/Inductive-Graph-Convolution-Network-for-Recommendation#5]
作者您好, 我对您的工作很感兴趣, 在阅读学习代码的时候对于IGCN 模型中inductive_rep_layer 实现逻辑产生了一些疑惑点, 希望得到作者的解疑. 
inductive_rep_layer 函数中调用了dgl.ops.gspmm 实现lightgcn 的消息传播聚合过程, 但实现图g 的过程中我有部分不了解.
```
row, column = feat_mat.indices() 
```
这里的col 是种子节点的种子index , 但并不是其原始index . 通过:
```
g = dgl.graph((col,row),num_nodes=max(self.feat_mat.shape),device=self.device)
```
构建图的时候, 网络拓扑结构发生了改变, 并不是原有图的一个子图, 那么其上的消息传播机制能不能保证节点embedding 的有效性? 

对于这一块, 我现在不确定是否存在理解上的差异?  希望得到解答 :)

**Comment by WuYunfan** [comment]
您好，感谢您对这篇工作的关注。
在IGCN的具体实现中，有feat_mat和norm_adj两个矩阵，具体用矩阵乘法的时候，是用了运行速度比较快的dgl（相比于pytorch原生和pyg实现的稀疏矩阵乘法更快）实现，其实我本意并不是想要在feat_mat的使用过程中构造一个图。那么具体到您列出的这两行代码，col对应的是模板用户/商品的index，row对应的却是所有用户/商品全局的一个index，所以严格来说这都不是一个图，同一个index的值在col和row中表示的不是同一个实体。我只是想借用dgl的这个函数实现矩阵乘法，很抱歉给您造成了疑惑。
