### ISSUE TITLE
请教一些理论上的问题

### ISSUE THREAD

**Issue by ithok** [WuYunfan/Inductive-Graph-Convolution-Network-for-Recommendation#6]
作者您好！

非常感谢您的工作，IGCN对我启发甚大。

有关您的这篇文章，我阅读了arxiv上的两个版本，现在关于文章内容和具体的代码实现，有一些疑惑始终难解，故厚颜向您请教：

1.首先是文章内容的理解，想请您帮我判断一下我的理解是否正确。
关于文章的theorem 4.1和4.2的证明，我看的不甚懂，如果您能提供更细致的解释我不胜感激，以下是我理解的部分，如果有错误还望您指正。
首先4.1是在论证，在模板用户和项目数量与输入一致的情况下（即Y不变的情况下),INMO-MF存在着一种Tu和Ti的取法，可以达到和MF低秩近似一致的交互矩阵误差。4.2在这个基础上，提出因为要取模板用户和项目，所以Tu和Ti不能像4.1一样那样取，而要引入矩阵C，C的引入导致了additional error，并证明了什么时候这个误差会最小，即errorsort indicator的由来。
这里的所谓误差，应该指的是MF的重建误差（和原始交互矩阵的差距），而不是具体的比如实际推荐的时候recall ndcg precision上的数值差距，不知这个理解是否正确？
（顺便我也很难理解类似的证法如何推到LightGCN上来）

2.error sort indicator的问题。是否您文章中的实验结果和公开的代码均是简化后的版本？
因为我在代码中没有发现其他版本的实现（这个可能是我阅读不仔细，如果有误，非常抱歉）。如果都使用了简化后的版本，theorem 4.1和4.2的结论是否有需要变动的地方吗？

3.文章5.3.1节，有关测试阶段考虑新的交互，测试阶段为什么能改善训练结果的原因。
因为我算刚入门这方面，这里应该是我水平太低的问题，所以我理解不了测试阶段考虑新的交互为什么能提升性能:)（测试参加了训练？）  能否请您简单的概述一下这里具体的做法、原理以及其所在的代码部分？

4.在选择全部数据集作为模板用户/项目的情况下，INMO和原始方法有哪些不同？
这个是我看到实验结果才想到的。因为我最开始觉得是没什么区别的，如果把全部数据集作为模板用户/项目，那参数规模就和原始一致，等同于lookup table，所有节点都需要学习embedding。但是在您文章中报告的实验部分报告的结果，INMO表现出了明显的提升，那是什么支撑了这些性能的提升呢？
具体来说，比如LightGCN，我想了解的是，在这种情况下（全部数据集作为模板用户/项目），和原始的方法相比，INMO有哪些做法上的变化呢？
我所能联想到的，大概就是INMO在进行邻域聚合时会默认连接的t_user和t_iem。（您5.2节提到的单射，对LightGCN来说应该是同样成立的，没记错的话LightGCN在进行邻域聚合时不包含自己）

5.有关文章总体的内容，INMO是否解释了在降参之下仍能取得性能提升的原因？
因为从常识性的判断来说，如果我们丢失了部分数据，那么推荐的精度应该会有所下降才是，但是INMO在30%的参数下实现了比原本算法更好的性能，这非常厉害，也是我认为您工作awesome的一个部分。但是，可能也有我理解能力的原因，文章好像并没有清楚地解释在降参之下仍能取得性能提升的原因。

可能有些冗长，还望您见谅。非常感谢您的工作，期待您的回复！

**Comment by WuYunfan** [comment]
1. 你理解的没有问题，理论分析一直是分析的MF的重建误差。因为LightGCN和MF一样都是embedding加线性模型，我认为是可以类似推导过去的，但也并没有实际为LightGCN推导过。
2. 实验结果和目前代码都是简化版本，非简化版本可以参考utils.py里被注释掉的部分，那里应该有最初版本的两个实现（分别对应是mean聚合和sum聚合模板用户/商品）。在使用简化版本后之前的结论不再能一定成立，简化版本是实现与理论的妥协。
3. 具体做法见run/dropit下的一些脚本。原理很简单，比如在训练阶段有一个用户买了A B C D四个商品，另一个用户买了A商品，如果我们在测试阶段知道了第二个用户新买了B C两个商品，那么模型就能更自信地给他去推荐D这个商品。
4. 在使用全部的用户/商品当做模板的情况下，INMO性能的提升来源于多加了一层聚合，额外的训练loss，训练过程中聚合函数的动态变化，全局模板的引入，以及单射的性质等等。LightGCN不聚合自己，但是它的最终表示是所有层的平均，包括最开始的embedding层，并没有单射的性质。
5. 简单地说，之前提到的一些优点实现了在“全部的用户/商品当做模板的情况下，INMO能带来性能提升”，然后在理论证明中，我们发现减少一定的参数量，MF重建误差提升的幅度可以比较小。所以在这两者的结合下，我们可以实现更少的参数以及更好的性能。
谢谢您对本工作的关注，如果还有任何关于这篇文章的问题，欢迎继续沟通。

**Comment by ithok** [comment]
好的，非常感谢您耐心的回复！

**Comment by ithok** [comment]
您好，我在阅读igcn的代码，请问有关于这个部分。
![image](https://user-images.githubusercontent.com/37830886/188941108-e17b20e2-a7b9-445c-b28c-2bc524530c50.png)
如果user是随机选取的怎么确保如公式10一样计算所有的loss呢？（而且我看idx也没有用上）

**Comment by WuYunfan** [comment]
您好，这里的idx在129行用上了。这里的idx主要是用于bce loss的实现中negative_sample_ratio不唯一的情况。你截图的这个函数在bpr loss的实现中只是采样一个正负样本用作比较，公式10要计算所有loss是不现实的（负样本非常多），具体实现中只能采样。你提到的这个问题是bpr loss实现的问题而不是igcn特有的，建议可以参考bpr loss的原文或者其他相关的文章。在我的理解中，基于比较的pairwise的loss中，负样本如何得到一直是CF领域比较关心的问题之一，不在本文的讨论范围内。

**Comment by ithok** [comment]
您好，是我问题表述出了问题，这里其实我想问的是index没有用上而不是idx，而是__getitem__(self, index) 里的这个index参数
因为pytorch我也只是了解大概，所以底层的知识可能并不是很正确。但是在我理解里，这个getitem函数pytorch要求的实现是能够进行给定dataset[index]返回对应的一个dataset中的一个data(姑且这么定义吧)，于是dataloader在__getitem__的基础上根据batch_size来分割batch的data。如果__getitem__(self, index)被实现成了按index取数据的版本的话，我可以理解最终所有的交互都会被考虑，但是igcn的设计给我的感觉是这里是随机的，也就是输入的index并没有起作用。
更简单的，我想表达的问题是:似乎这样的设计无法保证能遍历到所有的已有交互，即所有的正样本。因为作为正样本的用户是随机选定的，交互项目也是从已有随机选定的，这样一个epoch的所有batch数据中是否会出现相同正样本是我觉得不知道是否能成立的，同时我也觉得这样可能会漏掉一些交互。至于负样本采样，我同意您的观点。
您提到有关pairwise loss，负样本采样采多少，怎么采确实不是igcn需要顾及的，但在我的理解中，正样本应该是要遍历完全的，可能我的理解有偏差，因为我没有看过bprloss的原文也不清楚这些内容具体业界是怎么设计的，如果有问题还望您指正。
非常感谢！

**Comment by WuYunfan** [comment]
简单地说，正样本也是随机采样的，并不是输入index，就采样第index个交互，所以遍历一次dataset确实不能保证能考虑到所有的交互，也可能会有重复的正样本。这里这样实现正样本的采样，在我的实验中推荐效果是会比根据index采样好的。具体为什么会这样，根据我的理解是，这样的正样本采样方式保证了每次采样到的user的概率是相等的，而不是交互多的user会被采样到的次数更多，这种公平性可能保证一个更好的训练过程。

**Comment by ithok** [comment]
好的，感谢您的回复！
顺便问一下这种实现方式是您独创的还是有其他先例可循呢，因为我看的代码比较少，所以不清楚类似的实现一般是如何做的。

**Comment by WuYunfan** [comment]
关于这段代码的实现我是参考lightgcn的代码，详见https://github.com/gusye1234/LightGCN-PyTorch/blob/master/code/utils.py

**Comment by ithok** [comment]
我参照了您链接中的LightGcn的官方设计，如果我没理解错的话，确实IGCN和LightGCN都采用了相同的采样策略。
二者都不确保所有的正样本被采样到，且均采用了随机user采样的方式，区别在于，原版LightGcn的做法是直接对一个epoch的user进行采样，而您的做法是去实现了__getItem()__这个函数，然后用pytorch内置的dataloader和trainer实现具体的batch数据划分和训练，但既然二者的用户都是randint生成的，我的理解是这样的区别反映到结果上是一致的。
所以您算法的结果应该和原版是一致的。
还有一个小问题，因为我pytorch底层理解不是很深，所以我不是很确定您的实现每轮epoch中迭代训练的数据是否是相同的，这个问题的解应该取决于dataloader会不会在初始化之后再次调用__getitem()__，我找不到相关的解，不知道您是否有头绪呢？
非常感谢您的回复。

**Comment by WuYunfan** [comment]
getitem是在迭代dataloader的时候调用，而不是初始化的时候调用，每轮epoch的数据是不一样的，pytorch不会存储getitem返回的结果。

**Comment by ithok** [comment]
您好，想请教一下数据集的问题。
folder time和后面的folder 1，我在folder1上复现了您实验的结果。在进行超参数调整时，我使用了folder time的数据，按照介绍，1和time的差别在于一个是按时间顺序划分，还有一个是随机划分。我在两个数据集上遵循同样的设定，发现在folder time上无论是实验结果、收敛过程、难度还是过拟合的程度与1相比都差距甚大，不知道您是否有观察到这种现象？
我个人的理解是可能随机分布的序列会使得训练集和验证集和测试集的分布更相似，从而提升模型的泛化。

**Comment by WuYunfan** [comment]
不好意思我并没有注意到这个现象，其实一开始做的就是按时间划分的。但是为了做多个划分，重复多次实验，提升实验结果的可信度，所以采取了多个随机划分。在之前只做时间划分的实验中，我们的方法和baseline模型的比较排序应该与现在用随机划分的结果是相似的。

**Comment by ithok** [comment]
好的
