### ISSUE TITLE
关于Inductive Embedding Generation的问题

### ISSUE THREAD

**Issue by He-Yichen** [WuYunfan/Inductive-Graph-Convolution-Network-for-Recommendation#8]
作者您好，文章中公式(9)提出了调整嵌入的办法，想请教一下t_user和t_item是如何得到的呢？这个向量是所有模板用户/物品向量的平均或加和吗？
2.如果将所有的用户和物品作为模板，公式(9)中N_u∩I_tem是否就是等于N_u呢？
同时，我无法将这个公式和现在的代码对应上，模板用户/物品的特征向量应该如何训练呢？希望得到您的帮助！^ ^

**Comment by WuYunfan** [comment]
1. 这个向量是一个自由向量，可以自由学习，详见代码model.py 418行，定义的feat矩阵列数为user+item+2，其中的2是对应t_user和t_item。T矩阵在model.py 369行定义，大小与feat矩阵列数相关，可以自由学习。
2. 是的。

**Comment by He-Yichen** [comment]
> 1. 这个向量是一个自由向量，可以自由学习，详见代码model.py 418行，定义的feat矩阵列数为user+item+2，其中的2是对应t_user和t_item。T矩阵在model.py 369行定义，大小与feat矩阵列数相关，可以自由学习。
> 2. 是的。

非常感谢您的回复！
请问是否有对这个全局向量做消融性实验？相比起t_i和t_u的数量，一个全局向量的加入是否真的对性能有提升？

**Comment by WuYunfan** [comment]
没有针对这个做消融实验，当时加入全局向量只是觉得可能会有用，没有进行定量的分析

**Comment by He-Yichen** [comment]
> 没有针对这个做消融实验，当时加入全局向量只是觉得可能会有用，没有进行定量的分析

谢谢作者的解答^ ^
